### ISSUE TITLE
Rust example

### ISSUE THREAD

**Issue by suhr** [hwayne/lets-prove-leftpad#44]
I proved leftpad in rust, using [creusot](https://github.com/xldenis/creusot): https://github.com/suhr/leftpad

How to verify:

- `cargo creusot --span-mode=absolute -- --features=contracts`
- `«creusot repo»/ide target/debug/leftpad-rlib.mlcfg`

NB: you need to apply “Split VC” on the leftpad VC to avoid CVC5 timeout.

Creusot is a research software, so I'm not sure if I should make a PR yet.

**Comment by dhouck** [comment]
Oooh!  I tried with MIRAI in #43 and couldn’t get it to do even very simple things; I’m glad there’s another Rust solution now.

**Comment by suhr** [comment]
Known experience, a year ago I tried to prove leftpad using prusti, with no success. Creusot seems to be the first actually usable tool for deductive verification in rust.

**Comment by hwayne** [comment]
Make the PR!
