### ISSUE TITLE
Cryptol Version?

### ISSUE THREAD

**Issue by genos** [hwayne/lets-prove-leftpad#49]
Hi! Thanks very much for this repo & your write-up, I really enjoy them.

Would a [Cryptol](https://cryptol.net/) version be welcome? Here's a first attempt at one:

```cryptol
module leftpad where

leftpad: {pad, in, out}
         (fin pad, fin in, fin out, pad >= in, out == max pad in) =>
         Char -> String in -> String out
leftpad c s = repeat`{pad - in} c # s

leftpadLength: {pad, in, out}
         (fin pad, fin in, fin out, pad >= in, out == max pad in) =>
         Char -> String in -> Bit
property leftpadLength c s = length (leftpad`{pad, in, out}c s) == `out

leftpadPrefix: {pad, in, out}
               (fin pad, fin in, fin out, pad >= in, out == max pad in) =>
               Char -> String in -> Bit
property leftpadPrefix c s = take`{pad - in}(leftpad`{pad, in, out}c s) == repeat`{pad - in}c

leftpadSuffix: {pad, in, out}
               (fin pad, fin in, fin out, pad >= in, out == max pad in) =>
               Char -> String in -> Bit
property leftpadSuffix c s = drop`{pad - in}(leftpad`{pad, in, out}c s) == s
```

Though the `cryptol` REPL can prove things via the `:prove` command, it ["cannot directly prove polymorphic properties as they may hold for certain monomorphic instances while not for others."](https://cryptol.net/files/ProgrammingCryptol.pdf) For instance,

```cryptol
┏━╸┏━┓╻ ╻┏━┓╺┳╸┏━┓╻
┃  ┣┳┛┗┳┛┣━┛ ┃ ┃ ┃┃
┗━╸╹┗╸ ╹ ╹   ╹ ┗━┛┗━╸
version 2.13.0
https://cryptol.net  :? for help

Loading module Cryptol
Cryptol> :l leftpad.cry
Loading module Cryptol
Loading module leftpad
leftpad> :prove leftpadLength
Not a monomorphic type:
{pad, in, out}
  (fin pad, fin in, fin out, pad >= in, out == max pad in) =>
  [8] -> [in][8] -> Bit
(Total Elapsed Time: 0.000s)
leftpad> :prove leftpadLength`{10,3,10}
Q.E.D.
(Total Elapsed Time: 0.019s, using "Z3")
```

This can be nice in some respects; for instance, ```:prove leftpadLength`{10,3,0}``` throws an error about the unsolvable constraint `0 == 10`. That said, I'm not sure needing explicitly specify `pad`, `in`, and `out` yourself fulfills the spirit of this challenge.

Thanks again!

**Comment by hwayne** [comment]
I'd accept it under the condition that you explained, in the readme, what's meant by "cannot directly prove polymorphic instances", and why Cryptol chooses not to be able to prove them. Use the difference between what other FM tooling can do as a teaching opportunity for the repo reader!

**Comment by genos** [comment]
Cool! In that case, I'll get to work on a write-up & submission.
