### ISSUE TITLE
Lean solutions

### ISSUE THREAD

**Issue by bandali** [hwayne/lets-prove-leftpad#7]
Hey,

You missed these by @cipher1024, from a while back:

- [leftpad in Lean](https://twitter.com/bonhomme7heure/status/989619112010764288)
- [unique in Lean](https://twitter.com/bonhomme7heure/status/989625077133176832)

**Comment by hwayne** [comment]
My mistake! Sending him a link now.

In general I don't want to add the proofs myself, because I want each proof to have an explanation along with it.

**Comment by bandali** [comment]
Cheers!
